"""Constants for the zone component."""

CONF_PASSIVE = "passive"
DOMAIN = "zone"
HOME_ZONE = "home"
ATTR_PASSIVE = "passive"
ATTR_RADIUS = "radius"
ATTR_POINTS = "points"
ATTR_GEOMETRY = "geometry"
ATTR_TYPE = "zone_type"
TYPE_CIRCLE = "circle"
TYPE_POLYGON = "polygon"
