"""Constants for the OpenDisplay integration."""

DOMAIN = "opendisplay"
CONF_ENCRYPTION_KEY = "encryption_key"
CONF_DEEP_SLEEP_TIMEOUT_MARGIN_MINUTES = "deep_sleep_timeout_margin_minutes"

DEFAULT_DEEP_SLEEP_TIMEOUT_MARGIN_MINUTES = 7
MIN_DEEP_SLEEP_TIMEOUT_MARGIN_MINUTES = 0
MAX_DEEP_SLEEP_TIMEOUT_MARGIN_MINUTES = 24 * 60

SIGNAL_DEVICE_SEEN = f"{DOMAIN}_device_seen"
SIGNAL_PENDING_UPLOAD = f"{DOMAIN}_pending_upload"
